---

- name: Install pre-requesite
  apt:
    name:
      - openjdk-11-jdk
      - nginx
      state: latest
      update_cache: yes



- name: Add Elastic repository
  apt_key:
    url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Install APT repo
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes


- name: getting apt transport https
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present

- name: install elastic search
  apt:
    name: elasticsearch
    state: present
    update_cache: yes


- name: update the config file to allow authorization
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host:'
    line: 'network.host: localhost'

- name: update the port config file
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'http.port'
    line: 'http.port: 9200'

- name: Discovery type
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    line: 'discovery.type: single-node'

- name: Install kibana
  apt:
    name: kibana
    update_cache: yes

- name: update the config file to allow authorization
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'server.host: localhost'

- name: Defining server port
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'server.port'
    line: 'server.port: 5601'

- name: starting kibana
  srvice:
    name: kibana
    state: started

- name: install logstash
  apt:
    name: logstash
    update_cache: yes

- name: start logstash
  service:
    name: logstash
    state: started

- name: start elastic search
  service:
    name: elasticsearch
    state: started

