---

language: python
python: "2.7"


#use the new container infrastructure
sudo: false


# install ansible

addons:
  apt:
    packages:
      - python-pip

install:
  #install ansible
  - pip install ansible


  - ansible --version


  - printf '[defaults]\nroles_path=../' >ansible.cfg


script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

