---
# tasks file for eservice_debian
- name: INSTALL vsftpd
   state: latest
   update_cache: yes

- name: STOP FIREWALL
  service:
    name: ufw
    state: stopped
    enabled: no

- name: CREATE FTP USER
  user:
    name: nabiulaesd
    password: $9$y..4FgsTUtw/sdr3$oP/uHF^&ye67&R5tt67r2F6we5UIYHugubg.
    comment: "Create User !"

- name: ADD DENYUSER IN /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "DenyUsers nabiulaesd"
  register: sshd_config

- name: RESTART SSHD SERVICE
  service:
    name: sshd
    state: restarted
  when: ssh_config.changed

- name: CREATE FTP DIRECTORY
  file:
    path: /home/nabiulaesd/ftp
    state: directory 
    owner: nabiulaesd
    group: nabiulaesd
    mode: '0555'

- name: CREATE FTP DIRECTORY FILES
  file:
    path: /home/nabiulaesd/ftp/files
    state: directory
    owner: nabiulaesd
    group: nabiulaesd

- name: COPY vsftpd.conf
  copy:
    src: vsftpd.conf
    dest: /etc/vsftpd.conf
  register: vstpd_config

- name: RESTART vsftpd.conf
  service:
    name: vsftpd
    state: restarted
  when: vsftpd_config.changed

